version: "3.8"
services:
  openai-proxy:
    image: openai-proxy:latest
    restart: always
    container_name: openai-proxy
    ports:
      - "18770:18788"
    environment:
      - OPENAI_API_KEY=xxx
      - BASE_URL=https://api.siliconflow.cn/
      - PORT=18788
    extra_hosts:
      - "api.siliconflow.cn:106.14.246.150"
